
name: CI/CD Fullstack
#
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/my-project
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test -- --watchAll=false

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test

  deploy-frontend:
    needs: [frontend-tests, backend-tests]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/my-project
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./frontend/my-project/dist
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions ðŸš€"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-backend:
    needs: [frontend-tests, backend-tests]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
